services:
  php:
    build:
      context: docker/php
    environment:
      HISTFILE: /root/history/.history
      ENV: /root/.bashrc
    volumes:
      - .:/var/www/html:cached
      - php_history:/root/history

  postgres:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - postgres:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:3.10.2-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia:delegated
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  php_history: ~
  postgres:
  rabbitmq: ~
