services:
  php:
    build:
      context: docker/php
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      HISTFILE: /root/history/.history
      ENV: /root/.bashrc
    volumes:
      - .:/var/www/html:cached
      - php_history:/root/history

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: '!ChangeMe!'
      POSTGRES_USER: app
    healthcheck:
      test: pg_isready -d app
      interval: 10s
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia:delegated
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  php_history: ~
  postgres:
  rabbitmq: ~
